FROM php:8.0-fpm-alpine AS builder

WORKDIR /var/www/html

COPY composer.json /var/www/html
COPY composer.lock /var/www/html

RUN mkdir public
RUN apk -U --no-cache add curl
RUN docker-php-ext-install mysqli
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN composer install

FROM nginx:1.19
LABEL maintainer='Vincent Fricou <vincent@fricouv.eu>'

COPY docker/nginx/site.conf /etc/nginx/conf.d/
COPY include /var/www/html/include
COPY index.php /var/www/html
COPY --from=builder /var/www/html/public /var/www/html/public
COPY --from=builder /var/www/html/vendor /var/www/html/vendor
